import chex, optimistix, sympy2jax, sympy
import jax.numpy as jnp
import jax
import equinox as eqx
import jax.random as jr


class SympyEvaluator(eqx.Module):
    """
    A wrapper around a symbolic expression (via `sympy2jax`) for evaluating or optimizing symbolic models
    using JAX-compatible arrays.

    Attributes
    ----------
    expr : sympy2jax.SymbolicModule
        A JAX-compatible symbolic expression (e.g., generated by `sympy2jax.SymbolicModule`)
        that defines the structure and constants of the symbolic model.

    Methods
    -------
    __call__(x, y=None, mse=True)
        Evaluates the symbolic expression with inputs `x` and optionally computes the mean squared error with `y`.

    round()
        Returns a simplified version of the expression with constants rounded to 2 decimal places.

    Notes
    -----
    - Input variable names are automatically assigned in the form `x_0`, `x_1`, ..., `x_n` to match symbolic variables.
    """

    expr: sympy.core.Expr

    def __init__(self, expr):
        self.expr = sympy2jax.SymbolicModule(expr)

    def __call__(self, x: chex.Array, y: chex.Array = None, mse: bool = True):
        """
        Evaluates the symbolic expression on the input array `x`, optionally returning mean squared error (MSE)
        against target values `y`.

        Parameters
        ----------
        x : chex.Array
            Input data array of shape (..., D), where D is the number of input variables (up to 10).
        y : chex.Array, optional
            Target output values. Required if `mse=True`. Will be flattened internally.
        mse : bool, default=True
            If True, returns the mean squared error between predicted and target values.
            If False, returns the raw predicted values.

        Returns
        -------
        Union[float, chex.Array]
            - If `mse=True`: a single float representing the MSE.
            - If `mse=False`: an array of predicted values matching the shape of `x`.
        """
        input_shape = x.shape[-1]
        if mse:
            assert y is not None, "To calculate MSE, provide the target values y"
            y = y.ravel()

        # Build argument dict like {"x_0": x[..., 0], "x_1": x[..., 1], ...}
        arg_dict = {f"x_{i}": x[..., i] for i in range(input_shape)}
        ypred = self.expr(**arg_dict).ravel()

        return jnp.mean(jnp.square(ypred - y)) if mse else ypred

    def round(self):
        return self.expr.sympy().xreplace(
            sympy.core.rules.Transform(lambda x: x.round(2), lambda x: isinstance(x, sympy.Float))
        )

    def sympy(self):
        return self.expr.sympy()


def optimize_expr_constants(
    expr: SympyEvaluator, x: chex.Array, y: chex.Array, verbose: bool = False, tol=[1e-8, 1e-8], use_ls=True
) -> SympyEvaluator:
    """
    Optimizes the numerical constants of a symbolic expression using gradient-based least-squares minimization.

    Parameters
    ----------
    expr : SympyEvaluator
        A symbolic expression (wrapped in a JAX-compatible evaluator) with trainable constants.
    x : chex.Array
        Input data used to evaluate the symbolic expression.
    y : chex.Array
        Target values for regression, flattened internally to match the output shape of the expression.
    verbose : bool, default=False
        If True, prints the final loss and the number of optimization steps taken.

    Returns
    -------
    SympyEvaluator
        A new symbolic expression with optimized numerical constants, preserving the original structure.

    """
    if use_ls:
        try:
            temp_expr = optimize_expr_constants_ls(expr, x, y, verbose, tol)
            if not jnp.isnan(temp_expr(x, y)) and temp_expr(x, y) < expr(x, y):
                expr = temp_expr
        except:
            pass

    if expr.expr.sympy().is_integer:  # if expr is a single int, the minimize fails
        return expr

    params, static = eqx.partition(expr, eqx.is_inexact_array)
    y = y.squeeze()
    solver = optimistix.BFGS(tol[0], tol[1], norm=optimistix.max_norm)
    sol = optimistix.least_squares(
        grad_loss_least_squares, solver, params, args=(static, x, y), throw=False, max_steps=8192
    )
    if verbose:
        print(f"Final Loss BFGS: {grad_loss_minimize(params,args=(static, x, y) )}")
        print(f"Steps taken: {sol.stats["num_steps"]}")
    temp_expr = sol.value
    del sol
    temp_expr = eqx.combine(temp_expr, static)
    if not jnp.isnan(temp_expr(x, y)) and temp_expr(x, y) < expr(x, y):
        expr = temp_expr
    return expr


def optimize_expr_constants_ls(
    expr: SympyEvaluator, x: chex.Array, y: chex.Array, verbose: bool = False, tol=[1e-8, 1e-8]
) -> SympyEvaluator:
    """
    Optimizes the numerical constants of a symbolic expression using gradient-based least-squares minimization.

    Parameters
    ----------
    expr : SympyEvaluator
        A symbolic expression (wrapped in a JAX-compatible evaluator) with trainable constants.
    x : chex.Array
        Input data used to evaluate the symbolic expression.
    y : chex.Array
        Target values for regression, flattened internally to match the output shape of the expression.
    verbose : bool, default=False
        If True, prints the final loss and the number of optimization steps taken.

    Returns
    -------
    SympyEvaluator
        A new symbolic expression with optimized numerical constants, preserving the original structure.

    Notes
    -----
    - Optimization is performed using the `optimistix.BFGS` solver with high precision and `max_norm` stopping.
    - The loss function is mean squared error between the model prediction and `y`.
    - Useful as a post-processing step for improving symbolic fits from extracted expressions.
    """

    if expr.expr.sympy().is_integer:  # if expr is a single int, the minimize fails
        return expr
    params, static = eqx.partition(expr, eqx.is_inexact_array)
    y = y.squeeze()
    solver = optimistix.LevenbergMarquardt(tol[0], tol[1], norm=optimistix.two_norm)
    sol = optimistix.least_squares(
        grad_loss_least_squares, solver, params, args=(static, x, y), throw=False, max_steps=8192
    )
    if verbose:
        print(f"Final Loss Dogleg: {grad_loss_minimize(params,args=(static, x, y) )}")
        print(f"Steps taken: {sol.stats["num_steps"]}")
    expr = sol.value
    del sol
    expr = eqx.combine(expr, static)
    return expr


def grad_loss_minimize(params, args):
    static, x, y = args
    expr = eqx.combine(params, static)
    return expr(x, y, mse=True)


def grad_loss_least_squares(params, args):
    static, x, y = args
    expr = eqx.combine(params, static)
    y_pred = expr(x, mse=False).ravel()
    residuals = y.ravel() - y_pred
    safe_residuals = jnp.nan_to_num(residuals, nan=1e10, posinf=1e10, neginf=-1e10)
    return safe_residuals / y.std()


def perturb_and_optimize(expr, key, x, y, threshold, iterations=10, verbose=False):
    for _ in range(iterations):
        temp_expr = SympyEvaluator(perturb_constants(expr.sympy(), key))
        if jnp.isnan(temp_expr(x, y)):
            key = jr.split(key)[0]
            continue
        for _ in range(10):
            temp_expr = optimize_expr_constants(temp_expr, x, y, verbose=verbose, tol=[1e-10, 1e-12])
            if temp_expr(x, y, mse=True) < threshold:
                return temp_expr
        if temp_expr(x, y, mse=True) < expr(x, y, mse=True):
            expr = temp_expr
        if not jnp.isnan(temp_expr(x, y, mse=True)) and jnp.isnan(expr(x, y, mse=True)):
            expr = temp_expr
        key = jr.split(key)[0]
    return expr


def perturb_constants(expr, key, magnitude=0.5):
    """
    Recursively traverses a SymPy expression and perturbs all numerical
    constants using a log-uniform distribution (symmetric "jiggle").
    """
    if expr.is_Number:
        if expr.is_integer:
            return expr
        op_key, _ = jax.random.split(key)

        perturb_factor = jnp.exp(jax.random.uniform(key=op_key, minval=-magnitude, maxval=magnitude))
        return expr * float(perturb_factor)

    elif expr.is_Pow:
        base_key, _ = jax.random.split(key)
        new_base = perturb_constants(expr.base, base_key, magnitude)
        new_exp = expr.exp  # Keep the exponent as-is
        return new_base**new_exp

    elif not expr.is_Atom:
        # This is the bug-fixed key-splitting logic
        num_args = len(expr.args)
        if num_args == 0:
            return expr
        arg_keys = jax.random.split(key, num_args)

        new_args = []
        for i, arg in enumerate(expr.args):
            new_args.append(perturb_constants(arg, arg_keys[i], magnitude))

        return expr.func(*new_args)

    else:
        return expr


def rescale_expression_to_physical(scaled_expr, std_dev_map):
    """
    Converts a scaled SymPy expression back to its physical form.

    Args:
        scaled_expr (sp.Expr):
            The SymPy expression from your symbolic search,
            which uses normalized variables.

        std_dev_map (dict):
            A dictionary mapping the variables (as SymPy Symbols or strings)
            to the standard deviation of their ORIGINAL physical data.
            Example: {x1: 1e8, "x0": 1.0}

    Returns:
        sp.Expr:
            A new SymPy expression representing the physical equation.
            The *same* symbols (x0, x1) are used, but they now
            represent the physical variables, and the numerical
            constants in the expression have been correctly adjusted.
    """

    symbol_std_map = {}
    for key, std in std_dev_map.items():
        if isinstance(key, str):
            symbol_std_map[sympy.Symbol(key)] = std
        else:
            symbol_std_map[key] = std

    subs_dict = {}

    # We find all variables (free symbols) in the scaled expression
    for var in scaled_expr.free_symbols:
        std = symbol_std_map.get(var, 1.0)
        subs_dict[var] = var / std

    print(f"\n--- Applying Substitutions ---")
    for k, v in subs_dict.items():
        print(f"Replacing '{k}' with '{v}'")
    print("--------------------------------\n")

    physical_expr = scaled_expr.subs(subs_dict)
    return physical_expr.doit()


def integerize_exponents(expr):
    """
    Recursively traverses a SymPy expression and converts float exponents
    that are whole numbers (e.g., 2.0) into integers (e.g., 2).

    This "freezes" them, preventing eqx.partition from seeing them
    as trainable parameters.
    """
    if expr.is_Pow:
        # Recurse on the base first
        new_base = integerize_exponents(expr.base)

        new_exp = expr.exp
        # Check if the exponent is a Float that is a whole number
        if new_exp.is_Float and float(new_exp).is_integer():
            # Convert it to a SymPy Integer
            new_exp = sympy.Integer(int(float(new_exp)))

        return new_base**new_exp

    elif not expr.is_Atom:
        # Recurse on all other arguments (e.g., in Add, Mul, Sqrt)
        new_args = [integerize_exponents(arg) for arg in expr.args]
        return expr.func(*new_args)

    else:
        # It's an Atom (Symbol, Number, etc.), return as-is
        return expr


def backward_elimination(
    expr_eval: SympyEvaluator,
    x: chex.Array,
    y: chex.Array,
    max_error_increase: float = 0.01,  # Allow 1% error increase
    verbose: bool = False,
) -> SympyEvaluator:
    """
    Recursively removes terms from the expression, re-optimizes, and accepts
    the simplification only if the error does not increase significantly.

    Args:
        expr_eval: The starting optimized SympyEvaluator.
        x, y: The data to evaluate and fit on.
        max_error_increase: The allowed fractional increase in MSE (e.g., 0.01 for 1%).
    """
    current_expr = expr_eval
    baseline_loss = current_expr(x, y, mse=True)
    threshold_loss = baseline_loss * (1.0 + max_error_increase)

    if verbose:
        print(f"Starting Backward Elimination.")
        print(f"Baseline Loss: {baseline_loss:.6e} (Threshold: {threshold_loss:.6e})")

    while True:
        best_candidate = None
        best_candidate_loss = float("inf")
        sympy_expr = current_expr.sympy()
        floats = [n for n in sympy.preorder_traversal(sympy_expr) if n.is_Float]

        if not floats:
            break  # No more constants to remove

        # 3. Try removing each constant one by one
        for i, target_float in enumerate(floats):
            candidate_sympy = sympy_expr.xreplace({target_float: sympy.Integer(0)})
            candidate_sympy = sympy.simplify(candidate_sympy)
            if candidate_sympy == sympy_expr:
                continue
            candidate_eval = SympyEvaluator(candidate_sympy)
            candidate_opt = optimize_expr_constants(candidate_eval, x, y, verbose=False, tol=[1e-6, 1e-8])

            new_loss = candidate_opt(x, y, mse=True)
            if new_loss <= threshold_loss:
                if new_loss < best_candidate_loss:
                    best_candidate_loss = new_loss
                    best_candidate = candidate_opt
        if best_candidate is not None:
            if verbose:
                print(f"  Pruned term. New Loss: {best_candidate_loss:.6e} (Allowed: {threshold_loss:.6e})")
                print(f"  New Expr: {best_candidate.sympy()}")
            current_expr = best_candidate
        else:
            break

    if verbose:
        print("Backward Elimination Complete.")

    return current_expr
